project:
  type: website
  output-dir: docs

website:
  title: "My lifestory"
  favicon: favicon.ico
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Projects
      - href: Movie Reviews
        text: Outside of Work
      - href: reflection.qmd
        text: Reflection

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left



